### ISSUE TITLE
Converted JPG image is not transparent as the PNG image

### ISSUE THREAD

**Issue by Abhi011999** [EhtashamNaqui/PNG-to-JPG-converter#1]

**Comment by EhtashamNaqui** [comment]
JPG file format do not allow the image to be transparent. JPG format doesn't have transparency as property.
https://stackoverflow.com/questions/16906144/transparent-background-in-jpeg-image/16906178#:~:text=You%20can't%20make%20a,.NET%20(it's%20free).
![jpg](https://user-images.githubusercontent.com/42460290/85114037-e4cef280-b235-11ea-9191-440a2acf2dcf.PNG)
